feat/#45: join activity publishing
Kusitms-29th-Meetup-TeamE/Frontend pull request #48
Opened 2024-05-12 20:18 UTC by hyunn522

## 📝요약(Summary)
이슈 번호 : #45 

## 🔨변경 사항(Changes)

## 😉리뷰 요구사항

## 💎확인 방법 (선택)

<br/>

---
### 📌 PR 진행 시 이러한 점들을 참고해 주세요
    * P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
    * P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
    * P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-05-14 08:40 UTC, chamny20 requested changes
꽤 복잡한 작업이었을텐데 정말 수고많았어요!! 👍 천재만재 정서현
코멘트가 좀 많은데 저희의 눈부신.. 미래를 위해 꼼꼼하게 달아보았으니 천천히 확인해주시면 감사하겠습니다 ㅎㅎ,,

- 추가로 디테일 페이지 내의 슬라이드는 혹시 테스트 완료된 걸까요?

2024-05-14 08:40 UTC, chamny20 commented on src/app/join/detail/page.tsx
> +const page = () => {
p3: 다른 페이지에서도 그렇고 `page`로 네이밍을 통일하신 것 같은데, 제가 작성한 방식이랑 달라서 서로 통일하는 게 좋을 것 같다는 생각이 들어요~
어떻게 네이밍하는 게 더 보편적이고 바람직한지 서로 알아보고 통일하는 건 어떨까요?

2024-05-14 08:40 UTC, chamny20 commented on src/app/join/detail/page.tsx
p2: 해당 디테일 페이지는 아직 동적 라우팅이 적용되지 않은 걸까요? 
변경 사항에는 `/join/detail?id={id} 페이지 추가`라고 작성되어 있어서 여쭤봅니다!

2024-05-14 08:40 UTC, chamny20 commented on src/containers/join/ChipContainer.tsx
> +      className={clsx('py-[33px] pl-10 flex flex-col gap-7 border', className)}
p3: 요기 border은 임의로 작성하신 거 맞을까요?

2024-05-14 08:40 UTC, chamny20 commented on src/app/join/detail/page.tsx
> +        <textarea
p1: textarea도 다른 곳에서 많이 활용될 것 같아서 common-components로 빼는 게 좋을 것 같아요~ 다른 사용처에서 어떻게 활용되는 확인하고 작성해주실 수 있을까요?

2024-05-14 08:40 UTC, chamny20 commented on src/app/join/detail/page.tsx
https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes

2024-05-14 09:18 UTC, hyunn522 commented on src/app/join/page.tsx
> +            placeholder={'찾으시는 활동을 검색해보세요!'}
그 목적도 있긴 하지만, props인지를 확실히 구분하기 위해 중괄호를 붙였던 게 습관이 돼서 매번 붙이는 것 같아요
보통 안 붙이는 게 관례일까요?

2024-05-14 09:19 UTC, hyunn522 commented on src/components/join/ActivityHeader.tsx
Banner가 더 적절한 것 같아요 의견 감사합니다~

2024-05-14 09:20 UTC, hyunn522 commented on src/components/join/ActivityHeader.tsx
> +    <div className="w-full h-60 flex flex-col justify-center items-center border bg-center bg-cover bg-[url('/assets/components/activity-top-banner.png')]">
피그마 상에서는 일단 이미지가 같아서 바로 이미지를 넣긴 했는데 넘기는 게 더 좋은 로직일 것 같네요!
반영하겠습니다

2024-05-14 09:23 UTC, hyunn522 commented on src/components/common-components/chip/Chip.tsx
네 전체 칩을 선택에서 미선택으로 바꾸면 다른 칩들이 off되는 건 구현했어야 했는데..,. 깜빡했네요 ㅜㅜ
일단 이 부분만 해놓고 다른 부분은 기디 팀원분들한테 전달받으면 구현하겠습니다~

2024-05-14 09:33 UTC, hyunn522 commented on src/store/join/selectedJoinChipStore.ts
네 가능합니닷 페이지 처음 진입 시 `전체` 칩만 선택되어 있게 변경하겠습니다~
isInit 부분은 
활동 참여하기 페이지 왼쪽 상단에 있는 `관심활동 모아보기` 버튼 클릭했을 때, 선택돼있는 모든 칩이 off되어야 한다는 디스크립션을 구현하기 위함입니다!

2024-05-14 10:05 UTC, hyunn522 commented on src/app/join/detail/page.tsx
아 현재는 테스트 용으로 id가 1, 2인 데이터만 넣어놔서 첫번째와 두번째 아이템만 넘어가는 게 맞아요!
첨부해주신 레퍼런스처럼 url 형태를 `/detail/{id}`로 할 수도 있지만
query string으로 `/detail?id={id}`로 넘기는 게 더 직관적인 것 같아서~
detail 디렉토리 내부의 page 파일 보시면 paramId 추출해놓은 부분 있어서, 해당 id로 api 호출할 예정입니다

2024-05-14 10:07 UTC, hyunn522 commented on src/app/join/detail/page.tsx
> +const page = () => {
네 좋아요 컨벤션 나름 세세하게 정했는데도 추가로 정할 게 많네요., 회의에서 의논해봅시다!

2024-05-14 10:08 UTC, hyunn522 commented on src/components/common-components/modal/ModalClose.tsx
> +  isNotClosed,
네 맞아요 피드백 감사합니닷

2024-05-14 10:42 UTC, hyunn522 commented on src/components/join/JoinActivityModal.tsx
> +export type JoinActivityModalProps = {
좋아요~ types 디렉토리 내부에 ModalProps 파일 만들어서 빼는 거 어떨까요?

2024-05-14 10:44 UTC, hyunn522 commented on src/containers/join/ChipContainer.tsx
> +      className={clsx('py-[33px] pl-10 flex flex-col gap-7 border', className)}
네 개발 과정에서 임의로 넣은 거라 제거하겠습니다~

2024-05-14 10:46 UTC, hyunn522 commented on src/app/join/detail/page.tsx
> +        <textarea
네 현재 확인되는 건 마이페이지에서 후기 작성 시 쓰이는 부분이네요~ 완료한 후 다시 리뷰 요청드리겠습니다

2024-05-14 14:15 UTC, hyunn522 commented
> 꽤 복잡한 작업이었을텐데 정말 수고많았어요!! 👍 천재만재 정서현 코멘트가 좀 많은데 저희의 눈부신.. 미래를 위해 꼼꼼하게 달아보았으니 천천히 확인해주시면 감사하겠습니다 ㅎㅎ,,
> 
> * 추가로 디테일 페이지 내의 슬라이드는 혹시 테스트 완료된 걸까요?

꼼꼼한 코멘트 감사드립니다! 반영 완료해서 다시 리뷰 요청드려요~ (슬라이드 테스트도 완료됐습니다!)

2024-05-14 17:40 UTC, chamny20 commented on src/app/join/detail/page.tsx
`[논의 완료]`

2024-05-15 11:05 UTC, chamny20 commented on src/app/join/page.tsx
> +            placeholder={'찾으시는 활동을 검색해보세요!'}
아하 그렇군요~ 관례까지는 아닌 것 같은데, 보통 텍스트만 있을 때는 따옴표만 사용하는 걸 많이 봤어서 여쭤봤습니다!
크게 상관 없을 것 같아요 :)

2024-05-15 11:37 UTC, chamny20 approved these changes
피드백 꼼꼼하게 확인해주셔서 정말 감사합니다 ㅎㅎ 변경해주신 거 다 확인했고 잘 반영된 것 같아요~! 굿입니당
추가로 사소한 부분들은 제가 변경 후 커밋하였으니 한번 확인해주시면 좋을 것 같아요 :)
pull받은 후 아래 이슈만 한번 체크하고 넘어가면 될 것 같습니다!

[이슈]
- 슬라이드 arrow button 클릭 시 넘어가지 않는 것 같아요~
- `detail/1` `detail/2` 과 같이 아직 동적 라우팅 작업이 안된 것 같은데 확인 한번 부탁드려요!
- 필터링(chip) 부분은 api작업하면서 진행하는 거 맞을까요?

2024-05-16 01:42 UTC, hyunn522 commented
동적 라우팅은 작업했는데 푸시를 안했어서 추가해놓았습니닷
슬라이드 버튼 작업해봤는데 잘 안돼서.. 일단 후순위로 둬도 괜찮을까요?ㅜㅜ
칩 선택 관련 이슈도 아직 기획측에서 확답을 못 받아서 api 연동 브랜치에서 진행해야 할 것 같아요

2024-05-16 03:10 UTC, chamny20 commented
> 동적 라우팅은 작업했는데 푸시를 안했어서 추가해놓았습니닷 슬라이드 버튼 작업해봤는데 잘 안돼서.. 일단 후순위로 둬도 괜찮을까요?ㅜㅜ 칩 선택 관련 이슈도 아직 기획측에서 확답을 못 받아서 api 연동 브랜치에서 진행해야 할 것 같아요

넵 좋아요~! chat-api pr develop에 머지되고나서 충돌 해결하시면 될 것 같아요!

2024-05-16 14:06 UTC, merged